version: '3.1'
services:
  landoop:
    image: landoop/fast-data-dev
    ports:
      # - 2181:2181
      - 3030:3030
      - 8081:8081
      - 8082:8082
      # - 8083:8083
      # - 9581:9581
      # - 9582:9582
      # - 9583:9583
      # - 9584:9584
      # - 9585:9585
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1

  elasticsearch:
    image: elasticsearch:6.8.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node