version: '3.1'

networks:
    main:
        driver: bridge

services:
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   restart: always
  #   ports:
  #     - 2181:2181
  #   networks:
  #     - main
  #   environment:
  #     ZOO_SYNC_LIMIT: 5
  #     ZOO_TICK_TIME: 2000
  #     ZOO_SYNC_LIMIT: 5
  # kafka:
  #   image: wurstmeister/kafka
  #   command: [start-kafka.sh]
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   networks:
  #     - main
  #   environment:
  #     KAFKA_BROKER_ID: 0
  #     KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
  #     # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100  // for many broker
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  lenses:
    image: landoop/fast-data-dev
    networks:
      - main
    ports:
      # - 2181:2181
      - 3030:3030
      # - 8081:8081
      # - 8082:8082
      # - 8083:8083
      # - 9581:9581
      # - 9582:9582
      # - 9583:9583
      # - 9584:9584
      # - 9585:9585
      - 9092:9092
    environment:
      ADV_HOST: 127.0.0.1