version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_SYNC_LIMIT: 5
      ZOO_TICK_TIME: 2000
      ZOO_SYNC_LIMIT: 5
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100  // for many broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock